---
name: flux-local diff

on:
  push:
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  diffs:
    name: Compute diffs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster_path:
        - tests/testdata/cluster
        - tests/testdata/cluster2
        - tests/testdata/cluster3
        - tests/testdata/cluster4
        - tests/testdata/cluster5
        - tests/testdata/cluster6
        - tests/testdata/cluster7
        resource:
        - helmrelease
        - kustomization
    steps:
    - name: Checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - name: Setup Flux CLI
      uses: fluxcd/flux2/action@1fd61a06264d71cf445ed55c4f14d401d26a1c64 # v2.8.8
    - uses: ./action/diff
      id: diff
      with:
        path: ${{ matrix.cluster_path }}
        resource: ${{ matrix.resource }}
        debug: true
        sources: cluster=tests/testdata/cluster3,flux-system,home-ops-kubernetes
        api-versions: batch/v1/CronJob
    - name: PR Comments
      uses: mshick/add-pr-comment@8e4927817251f1ff60c001f04568532b38e0b4a0 # v3.11.0
      if: ${{ steps.diff.outputs.diff != '' }}
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        message-id: ${{ github.event.pull_request.number }}/${{ matrix.cluster_path }}/${{ matrix.resource }}
        message-failure: Unable to post kustomization diff
        message: |
          `````diff
          ${{ steps.diff.outputs.diff }}
          `````
