---
name: flux-local test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster_path:
        - tests/testdata/cluster
        - tests/testdata/cluster2
        - tests/testdata/cluster3
        - tests/testdata/cluster5
        - tests/testdata/cluster4
        - tests/testdata/cluster6
        - tests/testdata/cluster7
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - name: Setup Flux CLI
      uses: fluxcd/flux2/action@1fd61a06264d71cf445ed55c4f14d401d26a1c64 # v2.8.8
    - uses: ./action/test
      with:
        enable-helm: true
        sources: cluster=tests/testdata/cluster3,flux-system,home-ops-kubernetes
        path: ${{ matrix.cluster_path }}
        api-versions: batch/v1/CronJob
        debug: true
