---
name: Lint

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: codespell-project/actions-codespell@8f01853be192eb0f849a5c7d721450e7a467c579 # v2.2
        with:
          check_hidden: false
          exclude_file: ./tests/testdata/cluster9/clusters/dev/flux-system/gotk-components.yaml
      - name: Run yamllint
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3.1.1
        with:
          file_or_dir: "./"
          config_file: "./.yaml-lint.yaml"
          strict: true
      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: true
          cache-dependency-glob: "requirements_dev.txt"
          activate-environment: true
      - name: Install dependencies
        run: |
          uv pip install -r requirements_dev.txt

      - name: Run Ruff Check
        run: |
          ruff check --output-format=github .

      - name: Run Ruff Format
        run: |
          ruff format .

      - name: Static typing with ty
        run: |
          ty check . --ignore unresolved-import --ignore unused-type-ignore-comment --ignore invalid-argument-type --ignore invalid-assignment --ignore unsupported-operator --ignore invalid-method-override
